### ISSUE TITLE
All my kud disappeared?

### ISSUE THREAD

**Issue by Naturally-Delicious** [aurora-pro/apex-sigma-core#9]
When I check my kud, it is always 0 despite having some beforehand. I own a Discord server, and I recently changed a few permissions, and suddenly, all of my member's kud is gone. Help

**Comment by AXAz0r** [comment]
Please use GitHub only for development and functionality related issues.
For those with user bound data, visit our discord server by using this link: https://discordapp.com/invite/aEUCHwX
On the same server, a Kud reset was announced due to numerous changes regarding how Kud earning was handled out of extreme necessity due to performance reasons.

**Comment by Naturally-Delicious** [comment]
But my kud has been 0 for 3/2 days?? Is it supposed to stay at 0 even though we are active in the discord?

**Comment by AXAz0r** [comment]
**Alex** - 08/30/2017
@Critical @Info A strange combination of tags, i know.
**Great News**: I found what was slowing Sigma down and she should be fine for a long while. So yay for finally having stable performance back.
**Bad News**: Passive Kud and Experience earning has been disabled until further notice. Kud can still be earned with quizz minigames such as mathgame and anicg or unscramble as well as be used in fishing and the like.
With that, Kud costs for Fishing and Foraging have been removed.
And the announcement about the reset afterwards:

**Alex** - Last Saturday at 1:02 PM
@Critical Since the way Kud is earned has changed drastically.
Not being able to obtain it passively. A Kud reset is incoming!

Once again, please visit the official Discord server at the link above. i'm always free to chat and talk about anything that interests you, GitHub is simply not for issues such as this.
Thank you~

**Comment by Naturally-Delicious** [comment]
Sorry for bothering you. Thanks for the help

**Comment by AXAz0r** [comment]
Please, don't worry about it, drop by if you ever feel like it~
